# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Temzit Heat Pump"
  org.opencontainers.image.description: "Addon to receive data from Temzit Heat Pump"
  org.opencontainers.image.source: "https://github.com/pekishev/hass-temzit"
  org.opencontainers.image.licenses: "Apache License 2.0"
