# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Home Assistant add-on for Temzit Heat Pump
version: "latest"
slug: temzit
description: Addon to receive data from Temzit Heat Pump
url: "https://github.com/pekishev/hass-temzit/tree/main/hass-temzit"
arch:
  - aarch64
init: false
options:
  temzit_ip: null
schema:
  temzit_ip: "str"
hassio_api: true
services: ["mqtt:need"]
image: "ghcr.io/pekishev/{arch}-hass-temzit"
