name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Fix permissions
      run: chmod a+x -R hass-temzit/rootfs

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        build-args: BUILD_FROM=ghcr.io/home-assistant/aarch64-base:latest
        file: hass-temzit/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/aarch64-hass-temzit:latest
            
